registry: dockerproxy.artifactory-eu.mcp.mirantis.net/
controller:
  host: "{{ netris_web_api_url }}"
  login: "{{ netris_admin_username }}"
  password: "{{ netris_admin_password }}"
image:
  repository: jumpojoy/netris-operator
  tag: vs84
