---
apiVersion: ufo.mirantis.com/v1alpha1
kind: Network
metadata:
  name: pxe
  namespace: default
spec:
  vpc: Default
  type: evpn
  vlan:
    id: "300"
  evpn:
    type: l2
  tags:
    - ufo.mirantis.com
  gateways: []
  dhcp:
    enabled: false
  sites:
    - default
  tenant: Admin
---
apiVersion: ufo.mirantis.com/v1alpha1
kind: Subnet
metadata:
  name: pxe
  namespace: default
spec:
  vpc: Default
  cidr: 172.16.81.0/24
  tags: []
  network: pxe
  sites:
    - default
  tenant: Admin
